### ISSUE TITLE
When saving profile settings on mobile, there's no indication that the operation is in progress

### ISSUE THREAD

**Issue by jafd** [apxltd/what-bugs#1]
This way I've hit the Save Settings ~ 6 times, and after 10 seconds got 6 notifications that my settings were saved.

Not exactly good UX. I'd rather expect the button to become instantly disabled and captioned "Saving..." until the operation completes.

**Comment by BenLubar** [comment]
Added a spinner after the submit button while waiting for the server:

```
.nprogress-busy .form-actions:after {
    content: '';
    display: inline-block;
    width: 18px;
    height: 18px;
    vertical-align: middle;
    box-sizing: border-box;
    border: solid 2px transparent;
    border-top-color: #29d;
    border-left-color: #29d;
    border-radius: 50%;
    animation: nprogress-spinner 400ms linear infinite;
    margin-left: 10px;
}
```
