### ISSUE TITLE
Site trouble

### ISSUE THREAD

**Issue by dkfellows** [apxltd/what-bugs#100]
The site's down. Problems started at about 10:31 UTC, and consisted of degraded service  (some failures, responses taking about 10 times longer than usual) for about 15 minutes followed by total collapse (15 seconds to get a 599 response from nginx) at about 10:47 UTC. I'm guessing that something is hammering the site hard starting at 10:31 and that triggered a cache failure at 10:47.

I report this in the hope that it will allow you (with access to the logs) to figure out what actually happened. But it definitely looks like the problems were mitigated for a while to start out with (so yay for that…)

And as I wrote this, it came back online. Or not. The service appears to be very unstable.

**Comment by dkfellows** [comment]
Site became stable at 11:54 GMT. Happy log grepping!

**Comment by BenLubar** [comment]
No idea what the problem was, but I noticed kswapd using 99% CPU when I was able to ssh in, so presumably MongoDB was accessing its data in a way that the kernel couldn't predict. Did an apt upgrade, which included a new version of docker, so everything got restarted. Will continue to monitor.

**Comment by dkfellows** [comment]
Well, I'm guessing that the locus of the problem is external — a Bad Bot or something like that — and the core of the problem is cache-busting _somewhere_ (which is why the first 15 minutes were OK). Once the cache set tries to exceed memory, catastrophe ensues and kswapd will give those sorts of results. At that point, your chances of detecting what actually failed are minimal (and probably not important); the working set has exceeded memory and pain follows.

You should be able to see the pattern of problem accesses in the logs for the 15 minutes while things were still operational (e.g., by comparing with 15 minutes before that).
