### ISSUE TITLE
Remove acted-upon notifications

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#101]
The Notification notifier in the upper-right.  When I act on a notification-- clicking on it to follow through to a link, or "mark as read"-- the "stale" notifications should vanish from the list.  Either immediately, or after a set amount of time of being "acted on".  Not sure.

Issue is that the top 10 most recent notifications show.  I act on them.  Then, even though I have 40 notifications, the list just sits there with 10 stale entries.  I don't get a chance to quick-act on my older notifications.  At least not without going to /notifications, which defeats the point of having a quick-access icon.

**Comment by LB--** [comment]
It would help if unread notifications would move to the top - I've had cases where no matter how much I scroll I only see two out of three unread notifications, then only after reading those two the third is visible at the bottom somehow. The notification dropdown is literally buggier than Discourse's.

**Comment by BenLubar** [comment]
Acted-on notifications already go away after a week.

**Comment by halcyon1234** [comment]
I get a LOT of notifications in a week, which pile up and effectively make the Notifications area kinda useless.
