### ISSUE TITLE
Accessing wtdwtf/unread without authentication shows json instead of redirect

### ISSUE THREAD

**Issue by rjvdboon** [apxltd/what-bugs#103]
If you access https://what.thedailywtf.com/unread/ as an unauthenticated user you get a JSON blob

```
{"code":"not-authorised","message":"A valid login session was not found. Please log in and try again.","params":{}}
```

I would have expected a redirect to the login page.

**Comment by BenLubar** [comment]
Apparently this was fixed at some point.
