### ISSUE TITLE
Refresh banner incorrectly  appears for new-topics and watched-topics filters

### ISSUE THREAD

**Issue by LB--** [apxltd/what-bugs#107]
Before:
![image](https://cloud.githubusercontent.com/assets/1296838/14647169/20e74bec-0622-11e6-902d-c6715a5bb43a.png)

After clicking banner:
![image](https://cloud.githubusercontent.com/assets/1296838/14647184/336d1dfa-0622-11e6-9235-ce116862ac5c.png)

It's a very minor issue, but the banner to refresh should only appear when it applies to the current topic filter. I don't know how feasible it is, and it doesn't bother me if it never gets fixed.

Relevant to https://github.com/NodeBB/NodeBB/pull/4504

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4611
