### ISSUE TITLE
Streamed-in posts don't count as read

### ISSUE THREAD

**Issue by yamikuronue** [apxltd/what-bugs#108]
I keep having this situation:
1. Let's say a thread has 99 posts, and I last read post 95. It shows up in /unread
2. I click on it, and read four posts
3. While I'm on the page, a fifth post, very short, streams in
4. I have now read all 100 posts
5. I click /unread
6. It shows one unread post in that thread
7. I click the thread
8. It takes me to post 100 again

**Comment by BenLubar** [comment]
I think the bug here is that it sets the topic as read when you start reading it instead of when you get to the end.

**Comment by yamikuronue** [comment]
So what are we doing about it? I don't' see a sent upstream label here.

**Comment by BenLubar** [comment]
Whoops, forgot all about this one. Just a sec.

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4772
