### ISSUE TITLE
Youtube oneboxes don't work with time offsets

### ISSUE THREAD

**Issue by dkfellows** [apxltd/what-bugs#109]
It's occasionally nice to direct people to start at a particular point in a youtube clip. But the parsing of them for the oneboxing doesn't work at all; having a link like `https://youtu.be/ABCD1234ABC?t=27s` just results in the link itself being displayed, not the embeddable version.

It'd be even nicer if the start time was actually used.

**Comment by boomzillawtf** [comment]
Yes, this is a plugin issue. The plugin still needs some serious TLC. Discussion has been happening here:

https://what.thedailywtf.com/topic/19533/youtube-thumbnails

This is the plugin:
https://github.com/a5mith/nodebb-plugin-youtube-lite

**Comment by BenLubar** [comment]
Moved to a5mith/nodebb-plugin-youtube-lite#29
