### ISSUE TITLE
No space between allowed filetypes

### ISSUE THREAD

**Issue by coderpatsy** [apxltd/what-bugs#110]
![Image from thread](https://what.thedailywtf.com/uploads/files/1461428275864-ss-of-issue-resized.png)

".png,.jpg,.bmp" There should be spaces between those. Image is from [another bug report](https://what.thedailywtf.com/topic/19439/localisation-edit-settings-problem/11).

I'm a lurker too lazy to register so no idea if that's local to the reporter or already fixed with the reported bug or what.

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4614
