### ISSUE TITLE
Chat window goes behind header

### ISSUE THREAD

**Issue by loopback0** [apxltd/what-bugs#114]
![image](https://cloud.githubusercontent.com/assets/8740474/14828034/0bf9e77e-0bdd-11e6-9d65-be4c7fb79e42.png)

As title. The top of the window disappears behind the header - and when that happens, you lose the controls to move it back.

The only solution is to reload the page and reopen the chat window, which luckily doesn't remember its previous position.

**Comment by BenLubar** [comment]
Ok, this is because someone complained that menus opened behind the chat. So I'm just going to go ahead and disable that piece of CSS.
