### ISSUE TITLE
Streamed-in topic-lock event doesn't properly hide the "Reply" dropdown

### ISSUE THREAD

**Issue by Tsaukpaetra** [apxltd/what-bugs#116]
![image](https://cloud.githubusercontent.com/assets/1989056/14961908/18a60994-1051-11e6-8027-95f3d8495887.png)
The little blue dropdown button next to the "8 views" element was the Reply dropdown submenu. It still works and everything, just wasn't properly hidden when the stream came in that the topic was locked.

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4613
