### ISSUE TITLE
When in a (sub) category, "New Posts, Click here" does not refresh the category

### ISSUE THREAD

**Issue by pauljherring** [apxltd/what-bugs#117]
![image](https://cloud.githubusercontent.com/assets/3939886/14993039/dbb9f98a-1160-11e6-9b19-91db11026448.png)

Clicking that new posts button takes me to /unread - I'd expect 
1) That message to only refer to new posts in the category selected
2) When clicked, to take me to /unread?cid=&lt;whatever>

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4611
