### ISSUE TITLE
Unread notifications don't take you to unread posts

### ISSUE THREAD

**Issue by pauljherring** [apxltd/what-bugs#118]
While it's nice to know that people have posted to a thread you're watching...

![screenshot from 2016-05-05 13 30 00](https://cloud.githubusercontent.com/assets/3939886/15043517/a3e5b312-12c5-11e6-9dd5-967ce94fd686.png)

...clicking this should take me to the first of the 6 unread, not the last.

**Comment by BenLubar** [comment]
Is there any notification that should go to the target of the newest one in a merge?

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4610
