### ISSUE TITLE
Admin pages need transition spinners (was: Admin - menus don't work sometimes)

### ISSUE THREAD

**Issue by pauljherring** [apxltd/what-bugs#119]
Clicking this (from /admin in the title bar)...

![screenshot from 2016-05-05 13 34 38](https://cloud.githubusercontent.com/assets/3939886/15043610/49b9c9c2-12c6-11e6-8d7f-827101d409f4.png)

... changes the URL to /admin/manage/users/latest, but the page doesn't actually move from /admin.

Forced refresh takes me to the page then the menus start working as expected.

**Comment by BenLubar** [comment]
That page specifically sometimes takes a long time to load.

**Comment by boomzillawtf** [comment]
Ah, yes, being patient works. So there needs to be a loading spinner.

**Comment by pauljherring** [comment]
> That page specifically sometimes takes a long time to load.

I'm sure I've had problems with quite a few of the menus. I'd check to confirm, but for some reason, /admin is currently sending me to /login, even though I'm logged in....

**Comment by pauljherring** [comment]
> So there needs to be a loading spinner.

Ok - confirmed - this is needed.

**Comment by BenLubar** [comment]
The /login redirect is because of NodeBB/NodeBB#1972

**Comment by pauljherring** [comment]
> The /login redirect is because of NodeBB/NodeBB#1972

Ah - ok. Some explanation of why it's happening, on that page, might be useful....

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4609
