### ISSUE TITLE
Youtube Onebox should show title before playing

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#120]
I don't watch embedded videos.  Every.  100% of the time they destroy the page somehow.  Especially "one page apps".

The titlecard image should have the video title (so I know what the fuck it is), and that title should be a hyperlink to the Youtube video (so I can right-click open in new tab and watch it however the fuck I want).

**Comment by BenLubar** [comment]
Moved to a5mith/nodebb-plugin-youtube-lite#24
