### ISSUE TITLE
Mentions not preceded by whitespace aren't detected 

### ISSUE THREAD

**Issue by japonicus** [apxltd/what-bugs#123]
@mentions that are immediately preceded by punctuation aren't detected and linked. Notably this means that:

> (@mention1, @mention2 and @mention3)

only linkify mention2 and mention3.  Similar problems apply if the preceding character is anything but whitespace.

The suggestion dropbox appears even if the inserted mention isn't subsequently recognized. e.g.

![mention_test](https://cloud.githubusercontent.com/assets/207360/15098250/500117ba-1530-11e6-99e9-6e72de682449.png)

**Comment by BenLubar** [comment]
Moved to julianlam/nodebb-plugin-mentions#70
