### ISSUE TITLE
Search farts itself sometimes - example within

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#127]
Trying to search for the discopocalypse thread.  Entered search term "how can this be so wrong"

https://what.thedailywtf.com/search/how%20can%20this%20be%20so%20wrong?in=titlesposts

Spin spin spin spin OOOPS THERE'S BEEN AN ERROR HERE IS NO INDICATION OF WHAT IT IS OR AN INCIDENT ID OR ANYTHING.

**Comment by BenLubar** [comment]
We had some cooties just now. `18:15:29 up 30 days,  1:35,  1 user,  load average: 29.04, 13.58, 5.96`

I'm going to say this was a symptom of the cooties and not the cause of them.
