### ISSUE TITLE
Confirm login to access /admin requires password

### ISSUE THREAD

**Issue by pauljherring** [apxltd/what-bugs#128]
When trying to go to /admin, and you're prompted to confirm the account, it will not accept G+ (which is acceptable for a normal login) as a viable source of credentials - a password is required.

Either
1) If it's supposed to be allowed, it needs fixing
2) If it's not supposed to be allowed, stop showing them.

**Comment by BenLubar** [comment]
moved to NodeBB/NodeBB#4638
