### ISSUE TITLE
Forum is completely and totally fucked

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#129]
Load a page such as https://what.thedailywtf.com/topic/19930/world-of-vnc/137?page=8

See this in console: 

http://i.imgur.com/xsNUemq.png

Nothing clicky works at all.

**Comment by BenLubar** [comment]
@boomzillawtf this appears to be yours

**Comment by boomzillawtf** [comment]
What browser was this? I merged the pull request, but I've not been able to reproduce that on chrome, firefox or vivaldi.

**Comment by NedFodder** [comment]
@boomzillawtf 

> I've not been able to reproduce that on chrome, firefox or vivaldi.

Try using Firefox v22. :trolleybus:
