### ISSUE TITLE
Missing emojis

### ISSUE THREAD

**Issue by marczellm** [apxltd/what-bugs#13]
:fire:, :vader:, :shit: etc.

**Comment by BenLubar** [comment]
`:fire:` and `:vader:` work for me: https://what.thedailywtf.com/topic/19339/missing-emojis-13

`:shit:` looks like it's an _alias_ in https://github.com/Ranks/emojione/blob/master/emoji.json

Moving to NodeBB-Community/nodebb-plugin-emoji-one#2
