### ISSUE TITLE
URIError: Failed to decode param 'til-%EF%BD%81%EF%BD%82%EF%BD%8F%EF%BD%95%EF%BD%94-%EF%BD%94%EF%BD%88%EF%BD%85-%EF%BD%84%EF%BD%81%EF%BD%E2%80%99%EF%BD%8B-%EF%BD%81%EF%BD%E2%80%99%EF%BD%94%EF%BD%93-%EF%BD%8F%EF%BD%86-%EF%BD%88%EF%BD%94%EF%BD%8D%EF%BD%8C'

### ISSUE THREAD

**Issue by pauljherring** [apxltd/what-bugs#130]
Upon restarting NodeBB - log at http://pastebin.com/8vm7FDcw

**Comment by BenLubar** [comment]
It's an IP in Thailand with this user agent: `Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 OPR/26.0.1656.60`

**Comment by BenLubar** [comment]
Something's causing NodeJS to hit 100% CPU usage and then not accept any requests. It's not this.

**Comment by boomzillawtf** [comment]
Do we need to engage the NodeBB devs?

**Comment by BenLubar** [comment]
@pauljherring if the forum stops accepting requests and hits 100% CPU usage on both node instances and I'm not awake, `$ docker restart wtdwtf-nodebb`

@boomzillawtf at this point, I have no idea what's causing the problem.

The URIError isn't actually causing any problems - it doesn't crash the instance and it's in the HTTP server library, so NodeBB can't and shouldn't do anything about it.

**Comment by boomzillawtf** [comment]
It's the "no idea" part that says maybe we need some help. If nothing else, maybe post something here:

https://community.nodebb.org/category/16/technical-support

...and see if anyone has any ideas.

**Comment by BenLubar** [comment]
https://community.nodebb.org/post/50432

**Comment by pauljherring** [comment]
Ok,  that's the 100% reported.

Now about that URI....

**Comment by BenLubar** [comment]
@pauljherring it's just a stack trace, not a crash. Plus it happens completely inside the `express` library, so NodeBB can't catch it.

**Comment by pauljherring** [comment]
`E_CANT_FIX` then?

**Comment by BenLubar** [comment]
Yeah.
