### ISSUE TITLE
too much downtime

### ISSUE THREAD

**Issue by machado2** [apxltd/what-bugs#131]
The forum is getting offline too often and for too long.

**Comment by dkfellows** [comment]
See also https://github.com/apapadimoulis/what-bugs/issues/100 and https://github.com/apapadimoulis/what-bugs/issues/115

**Comment by LB--** [comment]
![image](https://cloud.githubusercontent.com/assets/1296838/19519857/451669da-95d3-11e6-950d-96a75c786a24.png)
