### ISSUE TITLE
Two copies of report bugs banner at top of page

### ISSUE THREAD

**Issue by devjoe2** [apxltd/what-bugs#132]
Ever since the downtime yesterday, when I open the page for a thread, I am seeing two copies of the banner bringing you to this site to report bugs. Please make pages have only one copy of the banner.
![twobanners](https://cloud.githubusercontent.com/assets/4087439/15576282/25c666fa-2325-11e6-8fe6-d7dd378ad824.png)

**Comment by BenLubar** [comment]
Moved to NodeBB/nodebb-theme-persona#281
