### ISSUE TITLE
Access-Control-Origin Header Bug

### ISSUE THREAD

**Issue by kking-envelope** [apxltd/what-bugs#133]
Cross Posted at: https://what.thedailywtf.com/topic/20041/access-control-origin-header-bug

**Expected:**

Things Work

**Actual:**

When navigating way from profile page, Errors abound!

**Steps to Reproduce:**

OS: Windows 10 Home
Browser: Chrome latest
Possibly Important Plugins: Ghostery:latest; Google Optouts:latest; HTTPS Everywhere:latest
Other: Porn Mode (a.k.a. Incognito)

1) Open Chrome.
1) Browse to WTDWTF
1) Log In
1) Click on Mailbox link

:See Screen Shot of Problem @ wtdwtf:

**Comment by BenLubar** [comment]
![](https://what.thedailywtf.com/uploads/files/1464281528138-upload-0a58f977-ac51-4fe8-8f64-9b26e49a82d7.png)

I can't reproduce that. On every browser I've tried (which is just Chrome) I get redirected to `https://` even in incognito.

**Comment by kking-envelope** [comment]
As I posted @ WTDWTF ... I'm guessing it's got something to do with my HTTPS Everywhere plugin. It sometimes does odd things to the protocol part of the URI.

I'd close this under NMFP.

**Comment by kking-envelope** [comment]
just tested to repro, and links were HTTPS, so I am 1000% not sure how I pulled that off ....

**Comment by LB--** [comment]
I also use HTTPS Everywhere, and don't have this issue. How in that screenshot did you get taken to the HTTP version of the site?
