### ISSUE TITLE
Forum: If you set the skin value to "", main page results in 404

### ISSUE THREAD

**Issue by alex-theman** [apxltd/what-bugs#134]
How to reproduce:
1. Alter one of the skin items to return a value of "".
2. Save settings.
3. Go to the forum's main page.

This is on: Firefox 46.0.1 under Windows 10

Interestingly, if you do this, you can change skins without refreshing, but the setting doesn't persist.
![/custom not found](https://cloud.githubusercontent.com/assets/1644295/15622471/f4fac4c2-2436-11e6-84c4-a096e6c9c492.PNG)

**Comment by BenLubar** [comment]
Are you sure it's not just because you have the home page setting set to custom with an empty location?

**Comment by alex-theman** [comment]
No, on the site What the Daily WTF, I set my theme/skin to "" through editing one of the skin list items in HTML, NodeBB freaked out and set my theme to what it thought was default, and that default breaks the main page and prevents me from changing my theme back. to the real default.

**Comment by BenLubar** [comment]
![screenshot 2016-05-28 at 10 32 03](https://cloud.githubusercontent.com/assets/4257305/15628136/777817fa-24bf-11e6-968f-139666c5b3c4.png)

I'm talking about this part of your settings.

**Comment by BenLubar** [comment]
I've changed your homepage from Custom:`custom` to None.
