### ISSUE TITLE
bug.title

### ISSUE THREAD

**Issue by pauljherring** [apxltd/what-bugs#136]
bug.body

mobile.screenshot: 

![screenshot_2016-06-01-14-01-01](https://cloud.githubusercontent.com/assets/3939886/15710334/8276e178-2801-11e6-86ac-af5dc3953e50.png)

**Comment by BenLubar** [comment]
![screenshot 2016-06-01 at 09 31 21](https://cloud.githubusercontent.com/assets/4257305/15713332/a5c35254-27db-11e6-83ac-85b18f260df2.png)
![screenshot 2016-06-01 at 09 35 35](https://cloud.githubusercontent.com/assets/4257305/15713487/3da78324-27dc-11e6-8fda-5d39727b3f23.png)

**Comment by pauljherring** [comment]
Shouldn't it default to English in the absence of a translation?

**Comment by boomzillawtf** [comment]
Plugins can specify a fallback language, but I don't think it does that in core. Yes, it's probably a bug, though then you'd also have people complaining that it showed things in the wrong language. I don't know what the right way of handling that should be.

**Comment by LB--** [comment]
Ideally the user could control the order of fallback languages, but that complicates the UI.

**Comment by BenLubar** [comment]
All variations of English now display this:

![image](https://cloud.githubusercontent.com/assets/4257305/16903691/6d855318-4c4a-11e6-8645-c347f74661d5.png)

RESOLVED_FIXED
