### ISSUE TITLE
unusable with poor internet  connection

### ISSUE THREAD

**Issue by machado2** [apxltd/what-bugs#137]
it frequently enters an invalid state were the reply buttons and pretty much any ajax call stop working, until a full refresh.

it happens so frequently that the forum is unusable.

the connection is good enough for any other website I test

**Comment by pauljherring** [comment]
I don't think a poor internet connection is the problem - the symptoms you describe have been noticed on decent connections as well: https://what.thedailywtf.com/topic/19922/need-to-refresh-to-reply
