### ISSUE TITLE
Home 404s

### ISSUE THREAD

**Issue by pydsigner** [apxltd/what-bugs#139]
How to reproduce:
Click on the "What the Daily WTF?" logo at the top or enter the URL https://what.thedailywtf.com/

Issue:
Get a page not found error

Expected result:
See the forum overview/home page

Bonus points:
The "Return to the home page." link in the 404 sends you right back to the 404ing page

**Comment by BenLubar** [comment]
Duplicate of #134, same resolution.

**Comment by pydsigner** [comment]
Sure enough, not sure how my home page got set to custom though. I only changed my theme and not the homepage.
