### ISSUE TITLE
Cannot differentiate posts in deleted topics

### ISSUE THREAD

**Issue by pauljherring** [apxltd/what-bugs#140]
Spammer. Two topics. One (topic) of which was deleted - which one?:

![screenshot from 2016-06-15 13-07-31](https://cloud.githubusercontent.com/assets/3939886/16079291/b85189e8-32fa-11e6-8bee-399268588b06.png)

I'd like to see some sort of differentiation as there is between when _**the posts themselves**_ have been deleted, for example:

![screenshot from 2016-06-15 13-12-50](https://cloud.githubusercontent.com/assets/3939886/16079340/f5c27544-32fa-11e6-8811-a79ad50a2ad0.png)

Whether it's the same CSS that applies, or different CSS, what I'd like is for CSS to differ between posts that are generally visible to members and posts that aren't. In this case so I can tell which spammy posts have been dealt with.

**Comment by BenLubar** [comment]
Sorry, this one was sitting in my inbox for a week and I forgot about it.

Moved to NodeBB/NodeBB#4780
