### ISSUE TITLE
Forum: Posts in read-only threads still have reply buttons if they are streamed in.

### ISSUE THREAD

**Issue by alex-theman** [apxltd/what-bugs#141]
![<pedant>Yet another reason to use the nodebb page view</pedant>](https://cloud.githubusercontent.com/assets/1644295/16090715/b022c3be-32fe-11e6-8819-7c808e933d1c.png)
By the way, I couldn't post anything to the thread, and got a "Action denied" message upon trying to post it.

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4758
