### ISSUE TITLE
Read notifications' text is unreadable under darkly

### ISSUE THREAD

**Issue by whjms** [apxltd/what-bugs#142]
Looks like the notification text colour is black:
![capture](https://cloud.githubusercontent.com/assets/3392687/16125684/b3641720-33c2-11e6-9737-ead4e5a2b6c0.PNG)

I'm not using any Stylish theme.

**Comment by BenLubar** [comment]
Duplicate of https://github.com/NodeBB/NodeBB/issues/4735#issuecomment-225926265
