### ISSUE TITLE
Cannot reply with highlighted quote to necro topic

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#145]
Go to a necro topic.

Highlight something.

Click REPLY.

Get "OMFG WHY U NECRO" popup, and click "Look, asshole, I want to necro this thread"

Composes appears, but no quoted reply.

**Comment by BenLubar** [comment]
I think it might be because the selection no longer exists once you click the "I want to fbmac this thread" button.

**Comment by halcyon1234** [comment]
Yes.  That's the bug.  

Even more annoying, after I click "I AM THE NECRO DEMON GOD LET ME POST"-- then the composer shows up.  If I then highlight and REPLY again (with the composer open, to add a quote)-- I get the necro popup AGAIN.  Even though I'm alreayd in the process of replying.

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4809
