### ISSUE TITLE
-1 others

### ISSUE THREAD

**Issue by LB--** [apxltd/what-bugs#146]
![image](https://cloud.githubusercontent.com/assets/1296838/16674340/ca51abee-447c-11e6-8412-356efffb2b1a.png)

https://what.thedailywtf.com/post/931002

Looks like Fox didn't even vote though? Maybe clicked twice.

**Comment by BenLubar** [comment]
Hey @boomzillawtf

**Comment by boomzillawtf** [comment]
I think I might be able to get to this next week.

Watch here for updates:
https://github.com/boomzillawtf/nodebb-plugin-upvote-notifications/issues/1

**Comment by BenLubar** [comment]
Moved to boomzillawtf/nodebb-plugin-upvote-notifications#1 I guess
