### ISSUE TITLE
Responsive composer redirects break navigation

### ISSUE THREAD

**Issue by Mivexil** [apxltd/what-bugs#148]
https://what.thedailywtf.com/topic/20475/responsive-composer-is-weird

Repro steps:
- Narrow your screen to force NodeBB into narrow-screen mode.
- Click "Reply".
- Composer opens on the entire screen. Your URL now starts with https://what.thedailywtf.com/compose?p=
- Make the screen wider. The composer goes back to normal, but the URL stays the same.
- Click the "go to the top of the topic" up-arrow in the header.

Expected result: I'm on top of the topic.
Actual result:

![https://what.thedailywtf.com/uploads/files/1468535597844-upload-be2c1175-0b8d-4645-a03c-52750ed39565.png](https://what.thedailywtf.com/uploads/files/1468535597844-upload-be2c1175-0b8d-4645-a03c-52750ed39565.png)

**Comment by boomzillawtf** [comment]
This only seems to trigger when you try to reply to a post. Replying to the topic in general doesn't seem to mess with the URL.

**Comment by Mivexil** [comment]
@boomzillawtf norepro, when in low-width mode (at 500px or so), both the global Reply button and Reply buttons under posts substitute the URL in the address bar.

I'm on Edge currently so that might be different, but I think it was the same with Chrome.

**Comment by BenLubar** [comment]
Moved to NodeBB/nodebb-plugin-composer-default#56
