### ISSUE TITLE
"Open outgoing links in new tab" setting not working

### ISSUE THREAD

**Issue by abarker-TDWTF** [apxltd/what-bugs#151]
When the "Open outgoing links in new tab" setting is enabled, outgoing links are opening in the same tab. First noticed on 13-10-2016.

WTDWTF topic: https://what.thedailywtf.com/topic/21133/links-open-in-same-tab-window-when-new-tab-option-is-enabled

**Comment by boomzillawtf** [comment]
It's a link inside an iFramely iframe. I'm not sure there's a way to do anything about this.

**Comment by iparamonau** [comment]
The link is inside NYTimes iFrame. I will reach them out to report the problem.

**Comment by iparamonau** [comment]
NYTimes team has resolved the issue now.
