### ISSUE TITLE
Missing translation(?) for user pages

### ISSUE THREAD

**Issue by LB--** [apxltd/what-bugs#152]
https://what.thedailywtf.com/user/ben_lubar
`[[pages:account/posts, ben_lubar]]`
![image](https://cloud.githubusercontent.com/assets/1296838/19359148/6f366c68-913e-11e6-8238-4b8f84a52b83.png)

**Comment by BenLubar** [comment]
https://github.com/NodeBB/NodeBB/commit/f519a3656094f01fe9da3748ce6a9f876e187607
