### ISSUE TITLE
Category icons in header not updating correctly

### ISSUE THREAD

**Issue by abarker-TDWTF** [apxltd/what-bugs#154]
So, the category icon seen within topics is stuck at whatever the category was since the last time I refreshed. I've tried refreshing a few times and it keeps happening, so I'm not sure what's going on.

In addition, each additional topic after the first adds it's category as a mini-icon at the bottom of the topic header. These mini-icons don't ever get removed from the header, even when in, say, the Unread view.

Here's a screencap taken after visiting a bug topic, two meta topics, and a Self-Serve Mafia topic:

![image](https://cloud.githubusercontent.com/assets/9084488/19577052/6ad1fdcc-96ca-11e6-8592-ec46bed0c387.png)

**Comment by yamikuronue** [comment]
![image](https://cloud.githubusercontent.com/assets/1219256/19577115/ce1c1e30-96e3-11e6-9cb6-d8998190c010.png)

Note that the thread I'm currently viewing is in the games category (orange icon). Abarker's thread is in the Mafia category (purple icon). But they're each showing a totally different icon.
