### ISSUE TITLE
Feature request: watch categories for realizies

### ISSUE THREAD

**Issue by yamikuronue** [apxltd/what-bugs#156]
Not sure if this is a plugin or what, but I would like a setting that, for a given category, makes every new thread in that category set to Watching until I disable that. 

Use case: the staff forum. I always want to see new threads there, but often they get buried in the noise.

**Comment by BenLubar** [comment]
> Use case: the staff forum.

Me too!

**Comment by boomzillawtf** [comment]
Yeah, I have the staff category set as my "Home" page for this reason. It's not as good as explicit notifications but is a helpful sort of work around.

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#5172
