### ISSUE TITLE
Can't see what I'm typing on Android

### ISSUE THREAD

**Issue by machado2** [apxltd/what-bugs#161]
The keyboard covers the text entry box and I can't see what I'm typing.

Julian said it's because of TDWTF custom CSS

**Comment by boomzillawtf** [comment]
I think the problem is that the chat popup on mobile is bigger than the screen size. On community.nodebb.org, it's the same size, so the close and settings are visible and the keyboard doesn't cover the edit box.

**Comment by machado2** [comment]
Original issue on NodeBB is https://github.com/NodeBB/NodeBB/issues/5700

**Comment by boomzillawtf** [comment]
Maybe this?
https://github.com/boomzillawtf/tdwtf/blob/bf31420d8930faa12c62040218666e0ac3aa2f29/plugins/nodebb-plugin-tdwtf-customizations/custom.less#L16

**Comment by boomzillawtf** [comment]
Or:
https://github.com/boomzillawtf/tdwtf/blob/bf31420d8930faa12c62040218666e0ac3aa2f29/plugins/nodebb-plugin-tdwtf-customizations/custom.less#L1103
