### ISSUE TITLE
/unread doesn't obey "no infiniscroll" setting

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#18]
I have "Paginate topics and posts instead of using infinite scroll" checked, and each Per Page set to 30.

Go to /unread, scroll down-- INFINISCROLL RIGHT IN THE FACE!

**Comment by BenLubar** [comment]
You have to do a hard refresh after setting that.

**Comment by halcyon1234** [comment]
Weird, because it works without a hard refresh on posts (I see the pagination controls there).

Just did a hard refresh, no-go on /unread, still infiniscrolling.

**Comment by BenLubar** [comment]
Oh, sorry. Misread.
