### ISSUE TITLE
Dark themes and the "Go to unread" thing don't play nicely

### ISSUE THREAD

**Issue by jaloopa** [apxltd/what-bugs#2]
![capture](https://cloud.githubusercontent.com/assets/3093252/13914704/0aabb534-ef48-11e5-840f-00bbd545e8c3.PNG)

**Comment by yamikuronue** [comment]
We have some Stylish rules for that: https://what.thedailywtf.com/topic/19207/can-we-have-an-official-nodebb-stylish-topic-now/ 

The skins were clearly added in from Bootswatch without testing or tweaking, so those rules might help with a starting place to adjusting the skins to make them make sense.

**Comment by coldandtired** [comment]
Not only dark themes. 'Paper' also does this even though most of the other skin problems (del/ins for example) are okay.

**Comment by yamikuronue** [comment]
Fun! The dark themes have numerous problems, but I didn't try Paper.

**Comment by yamikuronue** [comment]
....did you seriously close this based on Stylish existing?

**Comment by pauljherring** [comment]
LOL.

**Comment by jaloopa** [comment]
Doesn't help on mobile or Edge

**Comment by BenLubar** [comment]
The bootswatch themes are loaded directly from bootswatch's CDN, and there's no way of detecting which one the user has enabled. Without a complete overhaul of how this works, using Stylish is probably the only way that this can be worked around.

**Comment by jaloopa** [comment]
If the themes can't be made to work, then their inclusion is a bug. Sure, advanced users like us can use Stylish to mess with it, but that's no good for the majority of users, or people on browsers without extensions available. It's not a feasible workaround.

The ideal solution would be for the themes to include settings for things like text colour, toaster backgrounds etc.

**Comment by yamikuronue** [comment]
I think they should download the themes and include them in the codebase. Then I could make a PR to add a modified version of Darkly and of Superhero so that they actually fucking function. This white-on-white is the most unprofessional bullshit. 

Pardon the french.

**Comment by boomzillawtf** [comment]
Actually, you _can_ tell which one was enabled by detecting which CSS file is linked. For instance:

```
var s = [].slice.call(document.styleSheets);
var hasCustomStyle = false;
for(var ixs = 0; ixs < s.length; ixs++){
    sheet = s[ixs];
    if( sheet && sheet.href && sheet.href.indexOf('bootstrap') != -1){
        hasCustomStyle = true;
        break;
    }
}
```

It seems like a legitimate NodeBB bug to be shipping stuff that is known to not work like that. Also, NodeBB certainly knows which one was picked from the settings page.
