### ISSUE TITLE
Ctrl-Enter shows Preview instead of posting

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#23]
First: thanks for adding ctrl-enter to post.  A++ thank you.

Weirdness:  if I have Preview hidden and press CTRL-ENTER, instead of posting, it shows the Preview Window.  If I press CTRL-ENTER again, it posts.

**Comment by BenLubar** [comment]
That's what the documentation for the shortcut plugin says it does. CLOSED INVALID WONTFIX
