### ISSUE TITLE
"Go To Last Unread Post" on post listings on Desktop

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#24]
Apparently on the Mobile version of a list of posts, there's an icon to jump to the last unread post.

Can we have the same thing on Desktop?

Heck, even better, the thread title should just do that.  Because if I'm on /unread, and I click on something, then chances are 99.99999% that I want to go to the last unread post.

**Comment by LB--** [comment]
IMO jumping to the first unread post is much more useful than jumping to the last unread post.

**Comment by halcyon1234** [comment]
Blarg fucking shit mcassface I'M PRACTICING MY FRONT PAGE TYPOS DON'T MACROAGGRESS ME.

**Comment by BenLubar** [comment]
Superseded by NodeBB/NodeBB#4445 and NodeBB/nodebb-theme-persona#261
