### ISSUE TITLE
Emoji autocomplete doesn't find fa_ icons

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#26]
Autocomplete for :magic doesn't find fa_magic

Also, missing the :moon: iconset.

**Comment by halcyon1234** [comment]
The above should be :moon:

**Comment by halcyon1234** [comment]
FUCKING HELL!  Colon Em Oh Oh En Colon

**Comment by BenLubar** [comment]
moved to NodeBB-Community/nodebb-plugin-emoji-extended#5
