### ISSUE TITLE
Autojumping to last read post broke the back button

### ISSUE THREAD

**Issue by TheCatPlusPlus** [apxltd/what-bugs#30]
Tested on Chrome 49.0.2623.87 m, Firefox 47.0a2 (2016-03-22) on Windows.
1. Go into a thread where your bookmark is at the end (seems to need to be longer than couple posts, too, reproducible on e.g. status thread)
2. Click back button

Expected:

Goes back to page you entered the thread from (e.g. /unread or category view).

Actual:

Goes to topic URL with post ID removed, then promptly jumps back to last unread (well, since you just reentered the thread). You can go back with two quick back presses, but once I had this (no repro for that though) happen instead:

![](https://dl.dropboxusercontent.com/u/26824/ShareX/2016-03/2016-03-22_23-58-24.png)

**Comment by BenLubar** [comment]
ok, disabled that bit for now.

**Comment by BenLubar** [comment]
Superseded by NodeBB/NodeBB#4445 and NodeBB/nodebb-theme-persona#261
