### ISSUE TITLE
"Invalid Session" should probably not just be a toaster...

### ISSUE THREAD

**Issue by yamikuronue** [apxltd/what-bugs#32]
My session was almost certainly invalid; I awoke this machine from hibernate with an open page, and clicked a notification to go to a post without re-logging-in. I had the wrong banner up top, for pete's sake! But at the same time, instead of yelling at the user for something the software should be managing (session data), it should have quietly redirected me. 

![image](https://cloud.githubusercontent.com/assets/1219256/13984133/b95220a4-f0ca-11e5-9844-7c8368d58c83.png)

**Comment by yamikuronue** [comment]
You can barely see it, but my avatar is there, and my notifications and unread numbers, and my theme, but also "Log in to reply". But also "Watch"?

**Comment by BenLubar** [comment]
I'm pretty sure this only shows up if a server somehow loses all of its sessions without changing the cookie encryption secret. The reason it happened this time was that I moved the sessions to redis to fix NodeBB/NodeBB#4440

In hindsight, if I had known it would kill all the sessions, I would have changed the cookie encryption secret as well.

**Comment by yamikuronue** [comment]
I was mostly concerned that the software should, you know... take some kind of action, like taking me to a login page, instead of just complaining endlessly in toasters.
