### ISSUE TITLE
Feature Request: Replies indicator

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#34]
Filed under: let's not let Discourse do something better....

DiskHorse would show if a post had been replied to.  Even better, it would let you jump to those replies.

Benefit:  when reading a longer thread, you could tell if a post had been replied to long before you got to the end.  If I had a reply to someone, and the thread had been going on for a while, I could easily check to see if anyone had replied to them, and if so, if they had already said the thing I wanted to say.

I get that actually showing the posts inline would be a huge effort.  But it would be nice to have:
- Number of replies
- A way to jump to at least the first reply

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4608
