### ISSUE TITLE
Upvote widget counts are off

### ISSUE THREAD

**Issue by Onyx47** [apxltd/what-bugs#36]
Exhibit A: number of voters doesn't match the score:

![screenshot_2016-03-25-13-18-06_1](https://cloud.githubusercontent.com/assets/2098368/14044197/f2c40716-f28d-11e5-890f-8f1a9ec9445c.jpg)

Exhibit B: after hitting downvote:

![screenshot_2016-03-25-13-18-13_1](https://cloud.githubusercontent.com/assets/2098368/14044208/1c1be070-f28e-11e5-8eae-86a206e2e654.jpg)

Finding bugs by fatfingering stuff on mobile ftw!

**Comment by BenLubar** [comment]
![screenshot 2016-03-25 at 10 32 17](https://cloud.githubusercontent.com/assets/4257305/14047270/e251d07a-f274-11e5-879d-de70fb22843e.png)

Downvotes don't show up in the tooltip. The behavior you have seen is correct.

**Comment by Onyx47** [comment]
But...

_counts fingers_

Damn it!

**Comment by sjennison** [comment]
You could argue that this should be made a little more obvious though. I just have no idea how...
