### ISSUE TITLE
YouTube OneBox Issues

### ISSUE THREAD

**Issue by Choonster** [apxltd/what-bugs#37]
When a post with a YouTube onebox first loads, it displays the video's thumbnail (or this grey thing) without the video's title:
![wtdwtf_youtubeonebox1_2016-03-26](https://cloud.githubusercontent.com/assets/878073/14045805/3d671dae-f2f1-11e5-991e-008d5422ad10.PNG)

When the onebox is clicked the actual embedded player loads in, but displays with this terrible white bar next to it:
![wtdwtf_youtubeonebox2_2016-03-26](https://cloud.githubusercontent.com/assets/878073/14045804/3d3f84f6-f2f1-11e5-93bb-44f8f025ae1b.PNG)

The ideal behaviour would be to always show the title and never show the terrible white bar.

**Comment by BenLubar** [comment]
Fixed the white bar, but the title will need to be fixed upstream.

https://github.com/a5mith/nodebb-plugin-youtube-lite/issues

**Comment by Choonster** [comment]
Thanks Ben. I've opened an upstream issue [here](https://github.com/a5mith/nodebb-plugin-youtube-lite/issues/24).
