### ISSUE TITLE
Title of thread disappears when scrolling down thread, causing a weird disjointed experience where you're never sure where you are on the site

### ISSUE THREAD

**Issue by blakeyrat-dailywtf** [apxltd/what-bugs#41]
Steps to reproduce:

1) Open any thread longer than 20 posts or so
2) Scroll down

Expected results:

Navigation elements (most importantly the thread title and breadcrumbs) remain present on screen

Actual results:

All navigation elements disappear as you scroll down, creating a situation where you're virtually never quite sure what thread you're in, or how to get back to the category listing

**Comment by blakeyrat-dailywtf** [comment]
Note just the title of the thread, but if you're in "desktop view" the pager also disappears. So not only do you lose what thread you're in, but you also lose how far down you are in it.

**Comment by BenLubar** [comment]
On the desktop view, the top bar does not disappear. On the mobile view, you can scroll up slightly to make it reappear, just like every other mobile app that has a scrollable view with a self-hiding top bar.

https://www.youtube.com/watch?v=p_Y8AfJWXYs

The topic title is in the top bar.

**Comment by blakeyrat-dailywtf** [comment]
That is not true:

![image](https://cloud.githubusercontent.com/assets/18073711/14050498/7a55b69e-f279-11e5-9755-89efd6cb2b4d.png)

This is a browser window (made ridiculously wide to ensure desktop mode) and as you can see the top bar _has_ disappeared entirely.

As for mobile view, we can revisit when the mobile view is no longer shown to desktop users.

**Comment by blakeyrat-dailywtf** [comment]
Actually on further reflection, I do seem to remember the top bar stuck around a few days back. So there might have been a fix for this at one time, but it's not currently working.

**Comment by blakeyrat-dailywtf** [comment]
This appears to be mostly working, except see new bug about header lacking breadcrumbs.
