### ISSUE TITLE
You can't format text as underlined

### ISSUE THREAD

**Issue by blakeyrat-dailywtf** [apxltd/what-bugs#42]
Steps to reproduce:

1) In an editor, try to underline some text
2) Give up, because Markdown is hopeless and it can't be done

Expected results:

Typing text surrounded by underscores would create underlined text (if we're forced to use Markdown, at least that would make sense)

Actual results:

Markdown is utterly useless for this purpose; typing underscores actually produces italics somehow

**Comment by BenLubar** [comment]
[HTML still works](https://what.thedailywtf.com/topic/19469/underlined-text).

**Comment by blakeyrat-dailywtf** [comment]
Not according to the site's composer help lightbox.

**Comment by BenLubar** [comment]
fixed composer help lightbox to contain allowed HTML tags and attributes

**Comment by blakeyrat-dailywtf** [comment]
I don't get to verify fixes before it's closed?

**Comment by BenLubar** [comment]
I verified it on the test server and then I verified it again on live.

**Comment by blakeyrat-dailywtf** [comment]
In a normal development process, the person who makes the change is not the person who gets to verify it's indeed fixed.

If that's what we're doing, that's what we're doing, but it's a terrible practice.

**Comment by blakeyrat-dailywtf** [comment]
In any case, I can verify that HTML options are listed if not explained. Which is _good enough_, I suppose. I'm not sure why the heading over them is named "HTML Cleaner", why is the word "Cleaner" there?

**Comment by BenLubar** [comment]
That's the name of the plugin.

**Comment by blakeyrat-dailywtf** [comment]
Ok; but why is it there? Does the user need to know the name of the plugin?
