### ISSUE TITLE
Inscrutible options in Topic Tools menu

### ISSUE THREAD

**Issue by blakeyrat-dailywtf** [apxltd/what-bugs#47]
"Ask as question":

1) Casing is wrong (everything else in this menu is title case; this isn't for some reason)
2) Grammar is bad (ask _what_ as question? The topic? "Ask topic as question" sounds like a terrible command to give an infocom game, not a 2016 UI element caption. And as opposed to what? What other things can you ask that aren't questions?
3) No tooltip to explain what this does

"Mark as Solved":

1) Mysteriously, this _is_ title case
2) Grammar is bad, again
3) No tooltip to explain what this does, again

"Make this a normal topic":

1) Casing is wrong
2) "normal" as opposed to what? An abnormal topic?
3) No tooltip to explain what this does, again
4) When selected, shows "success! This topic is now a regular thread!":
 a) "regular" as opposed to what? Irregular?
 b) Why does a menu item that reads "normal topic" result in "regular thread"?

**Comment by BenLubar** [comment]
disabled `nodebb-plugin-question-and-answer`
