### ISSUE TITLE
Use of some items in Topic Tools menu shoot you to the top of the topic

### ISSUE THREAD

**Issue by blakeyrat-dailywtf** [apxltd/what-bugs#48]
Steps to reproduce:

1) Enter a long thread (at least 50 posts or so)
2) Select items from the Topic Tools menu

Expected results:

The posts stay where they are

Actual results:

Some items in the Topic Tools menu will shoot the page back to the top for no discernible reason

Notes:

Specifically, if you delete a post through the Topic Tools menu you get shot to the top. You appear to also get shot to the top if you "Ask as question", then "Make this a normal thread", although it only seems to happen sometimes? Not very consistent.

**Comment by BenLubar** [comment]
The nodebb-plugin-question-and-answer actions call ajaxify.reload. Not sure why.

/cc @psychobunny

**Comment by BenLubar** [comment]
disabled `nodebb-plugin-question-and-answer`
