### ISSUE TITLE
There's no way to mute/ignore a topic *or* a person

### ISSUE THREAD

**Issue by blakeyrat-dailywtf** [apxltd/what-bugs#51]
If a topic gets dumb and I no longer want to read it, there's no way of accomplishing that in NodeBB:

1) You can't "ignore" the topic so it won't appear on your Unread list
2) You can't in any way mute notifications from that topic, so you will still get notifications when someone replies to you in it
3) You also can't prevent an individual from sending you spam notifications, which is pretty easy because goddamned _everything_ sends a notification and they can't be turned off

**Comment by RaceProUK** [comment]
https://github.com/NodeBB/NodeBB/issues/4388 shoudl cover 1 and 2

**Comment by blakeyrat-dailywtf** [comment]
This isn't fixed (unless the UI is so obscure I can't find it at all.) Why is it closed?
