### ISSUE TITLE
Unread list doesn't have a way to filter new topics from topics that happen to have unread posts

### ISSUE THREAD

**Issue by blakeyrat-dailywtf** [apxltd/what-bugs#52]
My usual workflow when coming to the forum after logged off for a long while is to look at the topics with unread posts, read the few I'm actually interested in seeing, and use "Mark as Read" on the rest. Then I'd like to view the _new_ topics and do the same.

NodeBB has no way showing you new topics separately from existing topics with unread posts. Which means, I have no good way of reading _only_ new topics. Which also means it's quite easy to post duplicate topics, because there's no way to find whether a recent news item has been posted without looking through all 50+ of your unread topics.

**Comment by BenLubar** [comment]
NodeBB/NodeBB#4474

**Comment by blakeyrat-dailywtf** [comment]
This isn't fixed, why is this closed?

**Comment by LB--** [comment]
@blakeyrat-dailywtf You mean https://what.thedailywtf.com/unread/new doesn't work for you?
![image](https://cloud.githubusercontent.com/assets/1296838/15112985/42880ed6-15b7-11e6-9798-e7da621d7907.png)

**Comment by blakeyrat-dailywtf** [comment]
Without a discoverable UI, I didn't know that existed.

For a brief period, this functionality was linked to from a top-level tab. I assumed that tab was the intended way this would be implemented.
