### ISSUE TITLE
User avatar does two wildly different behaviors on two different screens

### ISSUE THREAD

**Issue by blakeyrat-dailywtf** [apxltd/what-bugs#53]
If you're looking at the list of Unread Posts, the user's avatar serves as some kind of mutant checkbox. (Also note that there is absolutely NO indication anywhere in the UI that this is the case. Absolutely zero discoverability.)

If you're inside a thread, it serves to open a brief description of the account.

Note that if you go to Topic Tools and select "delete posts", clicking the avatar next to a post will _not_ treat it like a checkbox, even though people would (reasonably, based on the behavior of the Unread Posts view) assume it did. In this mode, you have to click some of the text content of a post to select it.

**Comment by sjennison** [comment]
@BenLubar There's an issue open on NodeBB's tracker already - https://github.com/NodeBB/NodeBB/issues/4396

**Comment by blakeyrat-dailywtf** [comment]
This is not fixed. Why is it closed?

**Comment by boomzillawtf** [comment]
@blakeyrat-dailywtf, the actual issue where the code needs to be fixed is here now:
https://github.com/NodeBB/nodebb-theme-persona/issues/267'
