### ISSUE TITLE
Letters get cut off in signatures

### ISSUE THREAD

**Issue by Onyx47** [apxltd/what-bugs#56]
![https://u.pomf.is/xrjywy.PNG](https://u.pomf.is/xrjywy.PNG)

Notice the final `l` in the signature.

No repro on vanilla install, probably zalgo text prevention custom CSS messing it up

**Comment by BenLubar** [comment]
Strange, it has `overflow-y: hidden`, which shouldn't be doing anything to horizontal overflow.

**Comment by Onyx47** [comment]
No repro on my testing instance though, so it's probably something in our CSS.

![image](https://cloud.githubusercontent.com/assets/2098368/14060987/d89d5b2a-f374-11e5-835b-d50d69fbb02a.png)

**Comment by BenLubar** [comment]
Apparently Chrome doesn't know what `overflow-y` means. I'll add some padding on the right.
