### ISSUE TITLE
Can't specify syntax highlighting language

### ISSUE THREAD

**Issue by Choonster** [apxltd/what-bugs#57]
[This post](https://what.thedailywtf.com/topic/12236/the-official-status-thread/41433) specifies the code block's language as `lua` (directly after the opening ```, like on GitHub or Discourse), but it's displaying with SQL highlighting instead.

Is there a different way to set the language now?

**Comment by BenLubar** [comment]
fixed in the htmlcleaner plugin.

**Comment by Choonster** [comment]
That doesn't seem to have worked, my code now has no highlighting at all:

![wtdwtf_luacodehighlightingfailure_2016-03-27](https://cloud.githubusercontent.com/assets/878073/14063470/786dd5e0-f41e-11e5-955b-732c94d2d51d.PNG)

**Comment by BenLubar** [comment]
Unfortunately, the build of hljs included with nodebb-plugin-markdown does not include Lua. Or Go for that matter. :cry:

**Comment by Choonster** [comment]
Reported to the plugin [here](https://github.com/markdown-it/markdown-it/issues/219).

**Comment by puzrin** [comment]
@Choonster you need to ask nodebb guys, not markdown-it authors.

**Comment by Choonster** [comment]
Reported this to the [right place](https://github.com/julianlam/nodebb-plugin-markdown/issues/69) this time.
