### ISSUE TITLE
Discarding post on mobile doesn't dismiss editor

### ISSUE THREAD

**Issue by abarker-TDWTF** [apxltd/what-bugs#59]
When creating a post on mobile, clicking the X in the top left does not dismiss the editor and you must refresh the page to return to reading the topic. Then when trying to start a new post, the text of the dismissed post persists in the editor.

Noticed when using Chrome 49.0.2623.105 on Android 6.0.0.

**Comment by BenLubar** [comment]
fixed in local css.
