### ISSUE TITLE
Reply window flows beyond bottom of page

### ISSUE THREAD

**Issue by skotl** [apxltd/what-bugs#60]
Chrome 49.0.2623.87 on Windows 10.
I swear I saw this mentioned a while back so I'm surprised this is still an issue - perhaps to do with my screen res, which is 1920x1080.

When replying, the editor (and preview window) go beyond the bottom of the page.
Resizing the browser kinda fixes it in that I presume we switch to mobile mode and the browser displays a raw edit window.

![image](https://cloud.githubusercontent.com/assets/128320/14069005/0228fab4-f48b-11e5-93e2-7ef2a9d3e3b9.png)

**Comment by skotl** [comment]
Not a great screenshot; trust me in that there are eight lines of editable text there, but only six are visible.

![image](https://cloud.githubusercontent.com/assets/128320/14069020/69e81932-f48b-11e5-8fc1-7ca799a2cc15.png)

**Comment by LB--** [comment]
Does it still go off the bottom when you drag it up with the updown arrows icon in the top left corner?

**Comment by skotl** [comment]
Updown arrows?

Here’s a fullsize screenshot – can’t see the arrows you’re referring to.

[cid:image001.jpg@01D188E5.8B2437F0]

**Comment by pauljherring** [comment]
> Updown arrows?

![u](https://cloud.githubusercontent.com/assets/3939886/14076916/099432d4-f4de-11e5-9838-bb75b31fa624.png)

> Here’s a fullsize screenshot – can’t see the arrows you’re referring to.

`IMAGE_NOT_FOUND`

**Comment by skotl** [comment]
Apologies - I replied to the email, but githib ate the photo. Here's another attempt...

![image](https://cloud.githubusercontent.com/assets/128320/14076948/51a8bbda-f4de-11e5-88b3-31bb26760b91.png)

**Comment by pauljherring** [comment]
> Here's another attempt...

See that black circle with up/down arrows above the word "Replying" which itself is above the 'Bold' button....

**Comment by skotl** [comment]
Ahhh... roger that - yes, that fixes it.

Is this by design or a bug? It doesn't seem very elegant or discoverable behaviour.

Thanks for persisting!

**Comment by LB--** [comment]
It's by design so you can get the composer out of the way while you keep reading but haven't sent your post yet. Yes, it's not very discoverable.

**Comment by skotl** [comment]
Hmmm... in that case, should it default to being open, with the option to shrinkify and show the rest of the thread?
Given that 98% of the time when you start that operation it is to write rather than to read...?

**Comment by LB--** [comment]
Well the thing is, it _does_ default to being open for some people. I didn't even know it could be resized until people were complaining that it was off-screen for them.

**Comment by skotl** [comment]
Aha - once you've discovered the anti-discoverable expand button, it remembers that and opens expanded next time round.
So, crap design but by-design. so I'll hit close - thanks for the help, guys.
