### ISSUE TITLE
Images not shown after editing post

### ISSUE THREAD

**Issue by loopback0** [apxltd/what-bugs#64]
Before edit:
![image](https://cloud.githubusercontent.com/assets/8740474/14081081/b5a8cc0c-f500-11e5-8541-3d0c70353ca1.png)

After edit:
![image](https://cloud.githubusercontent.com/assets/8740474/14081083/b8fb11b2-f500-11e5-955d-45076ceeec42.png)

After refresh
![image](https://cloud.githubusercontent.com/assets/8740474/14081085/bc73ec6a-f500-11e5-864b-09efd3396422.png)

**Comment by BenLubar** [comment]
Repro'd and sent upstream: NodeBB/NodeBB#4487
