### ISSUE TITLE
Major Site Outage

### ISSUE THREAD

**Issue by dkfellows** [apxltd/what-bugs#66]
The site is very down and has been so for a substantial amount of time. This would have been a non-reportable SNAFU under Discourse, but with NodeBB it is indicative of a serious problem.

![image](https://cloud.githubusercontent.com/assets/1155878/14109639/e66fddac-f5ba-11e5-8e1a-52169d6ded08.png)

No idea what is wrong.

**Comment by LB--** [comment]
![image](https://cloud.githubusercontent.com/assets/1296838/14121135/cb2f4cde-f5bb-11e5-9855-4e0c33d1f0d5.png)

**Comment by BenLubar** [comment]
I disabled the notifications list and the cooties seem to have stopped.

And by "disabled" I mean I added this after [this line](https://github.com/NodeBB/NodeBB/blob/v1.0.2/src/user/notifications.js#L66):

```
                // TDWTF DEBUG 2016-03-29
                return callback(null, []);
```

/cc @julianlam

**Comment by julianlam** [comment]
Git hash plus applicable error stack traces please and thank you :smile:

**Comment by BenLubar** [comment]
@julianlam No stack traces, but I added this:

https://github.com/BenLubar/NodeBB/commit/117b8d2cb27cfc8874e8b92adaf1d453b26ef026

I updated from NodeBB 1783a07 to e99d952 during the cooties but they didn't stop until I disabled [that function](https://github.com/NodeBB/NodeBB/blob/v1.0.2/src/user/notifications.js#L66).

Here are some snippets from IRC:

```
13:54 < BenLubar> 29/3 18:53 [39] - warn: [socket.io] slow callback - 1044732ms 
                  - uid: [redacted] - ip: [redacted] - event: notifications.get 
                  - params: null - err: null
...
14:57 < BenLubar> 1174710ms for notifications.get
```

**Comment by BenLubar** [comment]
![image](https://cloud.githubusercontent.com/assets/4257305/14123294/70a78a4c-f5c5-11e5-8244-7ddc92e96cfd.png)

**Comment by BenLubar** [comment]
https://community.nodebb.org/topic/8396/issues-with-nodebb-perfomance

**Comment by julianlam** [comment]
Odd, if it was a crash from that bug, it would've been fixed in more recent commits.

**Comment by BenLubar** [comment]
Ah, I hadn't read the stack traces in that topic very closely. It is indeed a separate bug.

**Comment by dkfellows** [comment]
I do not know if the notifications thing was the problem or the symptom, but the continued performance difficulties would tend to indicate that it was merely the symptom. For example, I'm _currently_ seeing extremely long times to load small topics. Eventually I get a `504 Gateway Timeout` sometimes, or the topic loads. It's apparently arbitrary which happens.

Hunting performance problems can be hard. The only way to do it is to keep on improving the instrumentation you're applying to service calls in the hope of catching the trouble red-handed.

**Comment by LB--** [comment]
![image](https://cloud.githubusercontent.com/assets/1296838/14143440/d9dbfa8a-f650-11e5-8385-950104265a3c.png)

**Comment by DoctaJonez** [comment]
Do we know if the storm affected all 4 NodeBB instances, or just specific ones? If it affected all 4 instances simultaneously, that would tend to suggest a single point of failure, like Mongo db.

If the slowdown was in the Node backend, I'd expect individual instances to suffer while other instances are still OK.

Do we have any way of profiling the database and the node instances to see what's going on?

It'd be useful to profile the hosts to see if CPU, Memory, Disk access or Network bandwidth is being saturated.

**Comment by boomzillawtf** [comment]
Search may also be a factor. I remember it being very slow yesterday and at least one user reported cootie storms when he started searching.

**Comment by julianlam** [comment]
Is everything one one `t2.medium`? May be a better idea to put the database elsewhere if it isn't already.

**Comment by llouviere** [comment]
Timetable on enabling notification dropdown?

Is there an alternative?

**Comment by BenLubar** [comment]
![screenshot 2016-03-30 at 11 23 53](https://cloud.githubusercontent.com/assets/4257305/14149520/2a4cf136-f66a-11e5-9640-ac6344743d86.png)
![screenshot 2016-03-30 at 11 22 38](https://cloud.githubusercontent.com/assets/4257305/14149522/2a51821e-f66a-11e5-93e3-cdda69645c20.png)
![screenshot 2016-03-30 at 11 20 43](https://cloud.githubusercontent.com/assets/4257305/14149521/2a51105e-f66a-11e5-9c21-9199941f0834.png)

It looks like we need more disk IO operations per second allocated.

**Comment by AccaliaDeElementia** [comment]
ouch, yeah that disc queue length is.... off the charts. ideally you want that sucker sollidly under 1.0, we seem to be north of 10 regularly.... no wonder we have issues!

**Comment by AccaliaDeElementia** [comment]
@llouviere alternative for notifications?

i think i can come up with something...

**Comment by LB--** [comment]
Forums seem to be completely offline. SSL error over HTTPS and 404 over HTTP. Maintenance, I assume?

**Comment by BenLubar** [comment]
I stopped the AWS instance so I could snapshot the disk. Currently about 50% done. I hope the IP won't change when it comes back up.

**Comment by llouviere** [comment]
We could just use GitHub for our forums.

Pretty good reliability here.

**Comment by pauljherring** [comment]
=-o

**Comment by LB--** [comment]
![image](https://cloud.githubusercontent.com/assets/1296838/14159383/2e200894-f69b-11e5-9840-c5b1e5bbe9fd.png)

**Comment by julianlam** [comment]
@BenLubar Any chance you can just use nginx to send Googlebot a 503 temporarily?

http://stackoverflow.com/questions/2786595/what-is-the-correct-http-status-code-to-send-when-a-site-is-down-for-maintenance

**Edit**: Maybe they'll respond to an [HTTP 429](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429)

**Comment by BenLubar** [comment]
I've rate limited anyone with a user-agent matching /(bot|spider|slurp|crawler)/i to 1 request every 10 seconds (per IP) in nginx.

**Comment by BenLubar** [comment]
Looks like the rate limiting handled the bots and the better disk handled the large number of humans.

**Comment by dkfellows** [comment]
And another one; this one has been about an hour long so far (and started about 5 minutes before I attempted to use the site).

![image](https://cloud.githubusercontent.com/assets/1155878/14242994/d8a89396-fa4a-11e5-937a-71caced00cc5.png)

**Comment by DoctaJonez** [comment]
Does this need opening as a new issue so it gets noticed?  I think it was possibly a bit optimistic closing it in the first place.

The site seems to have been down for quite some time now.

(cc @BenLubar)

**Comment by BenLubar** [comment]
I just woke up and the site seems fine right now. Here's a graph:

![screenshot 2016-04-04 at 08 09 43](https://cloud.githubusercontent.com/assets/4257305/14248957/0918cd56-fa3d-11e5-95cd-1254fe1a3470.png)

**Comment by AccaliaDeElementia** [comment]
so.... what happened between 0230 and 0440 then?

**Comment by DoctaJonez** [comment]
> so.... what happened between 0230 and 0440 then?

Could it be backups? Maintenence plans (log file purging, etc)? Software updates?

**Comment by AccaliaDeElementia** [comment]
could be any of them. i asked because i don't know what it was and want to.

:-P

**Comment by dkfellows** [comment]
It hit again this morning (and is still ongoing as I write this) commencing at about 07:50 GMT. The nginx front-end seems to be sometimes fast to respond and sometimes not, like there's a resource exhaustion problem, but the back-end is solidly not responsive.

**Comment by dkfellows** [comment]
Also, I assume you have read http://redis.io/topics/lru-cache about `maxmemory` tuning? If not, you _really need to_ as redis defaults to being a memory hog.

**Comment by BenLubar** [comment]
`maxmemory` has been set to `100mb` and `maxmemory-policy` to `allkeys-lru` since before this last set of cooties started.

**Comment by julianlam** [comment]
@BenLubar output of `ss -s`? Run `mongostat` and see if there are items in the mongo write/read queue...
