### ISSUE TITLE
After 502, The notification icon shows positive count, clicking shows no notifications.

### ISSUE THREAD

**Issue by llouviere** [apxltd/what-bugs#67]
For a long time, the forum's address gave me 502 errors.

When I come back, the notification area shows a positive count, but clicking on it says "You have no new notifications"

"Mark all notifications read" option is available, and clicking it clears the icon and resets the count.

![image](https://cloud.githubusercontent.com/assets/5312876/14124895/c81a5f18-f5cd-11e5-97ad-02d99d8be821.png)

**Comment by LB--** [comment]
https://github.com/apapadimoulis/what-bugs/issues/66#issuecomment-203088486

**Comment by llouviere** [comment]
I observed this after you posted it.

To save you some trouble, could you consider put up a top-level warning alert box, next time?

I mean, up to you guys.
