### ISSUE TITLE
Loading a new topic with images in the OP overscrolls

### ISSUE THREAD

**Issue by LB--** [apxltd/what-bugs#68]
For example in [this thread](https://what.thedailywtf.com/topic/19437/click-next-to-continue-enjoying-your-4k-monitor) which I had not visited before, I opened it and it scrolled me down to below the bottom of the original post. This has happened on multiple threads and it always seems to happen when there are images in the post, though it may also happen all the time - images or not - and the images just make it more noticeable. Either way, it's confusing.

**Comment by julianlam** [comment]
[Latest tweaks to jellypotato detection](1783a07067dff9303ba92e753b40b46d3eb81114) made things worse, will revert

**Comment by BenLubar** [comment]
That link is NodeBB/NodeBB@1783a07067dff9303ba92e753b40b46d3eb81114 for anyone from the future.

**Comment by julianlam** [comment]
I've already fixed it and simplified the logic a little bit.

I couldn't run the final test to verify all use cases are accounted for, because the images I used suddenly couldn't load due to a DNS error that nobody else saw, so I'm taking that as a sign to go to bed.

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/1385d19f64ec03f9e08d4621e609cd6dbfa72ac9

**Comment by LB--** [comment]
If it happens again I'll reopen this issue
