### ISSUE TITLE
HTML Sanitizer unnecessarily closes tags

### ISSUE THREAD

**Issue by yamikuronue** [apxltd/what-bugs#7]
As reported by Maciej: https://what.thedailywtf.com/topic/19332/html-sanitizer-unnecessarily-closes-tags 

```
Repro: type the following

<test> is a tag

Result:

<test> is a tag</test>
```

This hampers discussion of tags, as they can't be talked about without being closed

**Comment by LB--** [comment]
I think @BenLubar said that this was his doing.

**Comment by yamikuronue** [comment]
I figured, hence entering it here

**Comment by BenLubar** [comment]
Fix written and tested. Will be applied later today.
