### ISSUE TITLE
Styling keyboard shortcuts don't work in composer

### ISSUE THREAD

**Issue by abarker-TDWTF** [apxltd/what-bugs#75]
Shortcuts such as <kbd>Ctl</kbd>+<kbd>B</kbd> for **Bold** and <kbd>Ctl</kbd>+<kbd>I</kbd> for _Italic_ don't work in the post composer.

**Comment by BenLubar** [comment]
From the admin panel:

> WRITING A POST
> 
> Send post
> +
> Discard post
> 
> Shift + Escape
> +
> Toggle preview visibility
> +
> Show preview or send post if already shown
> 
> Ctrl + Enter
> +
> Show help
> +
> Show write-tab (deprecated)
> +
> Make selected text bold
> +
> Make selected text italic
> +
> Make selected text a list-item
> +
> Make selected text a link-name
> +
> Focus title-field (opens closed composer)
> +
> Focus textarea (opens closed composer)
> +
