### ISSUE TITLE
Loading in middle of topic with missing title slug

### ISSUE THREAD

**Issue by abarker-TDWTF** [apxltd/what-bugs#76]
It appears that on sufficiently long topics, when the topic loads to the last read position, the title slug in the header doesn't load. For example, here I loaded in What happened to Discourse? at post 20 and got no title slug:

![0_1459448385958_upload-191e9d25-17ee-4adc-91f2-662f596de953](https://what.thedailywtf.com/uploads/files/1459448440364-upload-191e9d25-17ee-4adc-91f2-662f596de953) 

Scrolling up so that the Topic breadcrumb is visible and scrolling back down fixes it, but that isn't always a viable fix.

Even loading directly to post 5 seems to cause the issue:

https://what.thedailywtf.com/topic/19550/can-we-throw-money-at-the-problem/5

![0_1459448538885_upload-dffe62cc-eb13-4ade-a93b-9f5b4d1088df](https://what.thedailywtf.com/uploads/files/1459448593356-upload-dffe62cc-eb13-4ade-a93b-9f5b4d1088df) 

Chrome on Windows 7

**Comment by BenLubar** [comment]
I reported it here: https://github.com/NodeBB/NodeBB/commit/3a27e7b0ea527dfe8bfbb84e8899e50016205910#commitcomment-16915547

but if you'd like, it can also be reported more formally.

**Comment by abarker-TDWTF** [comment]
¯\_(ツ)_/¯ I just saw it hadn't been logged here and figured it should be so we had an accurate log.

**Comment by BenLubar** [comment]
Fixed locally with some JavaScript that is TRWTF, but still not fixed upstream.
