### ISSUE TITLE
Images are not responsive on mobile

### ISSUE THREAD

**Issue by julianlam** [apxltd/what-bugs#78]
![selection_040](https://cloud.githubusercontent.com/assets/923011/14211922/8a94ce70-f7fe-11e5-8be6-87613a4bb104.png)

Due to

![selection_041](https://cloud.githubusercontent.com/assets/923011/14211927/8df862fc-f7fe-11e5-9559-ee2af46532e5.png)

Suggest wrapping your override in media query to target devices > 600px width only

**Comment by BenLubar** [comment]
`max-width` is now only overridden on screens that are at least 1000px wide.
