### ISSUE TITLE
Post submit button has weird menu

### ISSUE THREAD

**Issue by dkfellows** [apxltd/what-bugs#86]
When writing a post, the submit button has this weird menu-like thing attached to it. That menu-like thing has only one item on it and appears to be completely useless; there is absolutely nothing useful that I can do with it.
![1459874901264-upload-baa69b80-db56-4020-8822-16e6fc36a4b4](https://cloud.githubusercontent.com/assets/1155878/14311368/da1fa350-fbde-11e5-96ff-30c7dfe165f7.png)
Why show the menu to users when there is nothing useful they can do with it? It's just a confusing user experience. (Note that if it is useful to admins and/or moderators that's one thing, but please think about non-admin/non-moderator users too.)

**Comment by dkfellows** [comment]
I suspect this is something to send upstream…

**Comment by pauljherring** [comment]
It's a moderation menu that I suspect shouldn't be shown to non-moderators, and has been mentioned before:

![screenshot from 2016-04-06 10 09 17](https://cloud.githubusercontent.com/assets/3939886/14311532/c03027ca-fbdf-11e5-9518-d26de4af636d.png)

[An obvious search](https://github.com/NodeBB/NodeBB/search?utf8=%E2%9C%93&q=submit+&type=Issues) isn't pulling any obvious results from upstream however.

**Comment by dkfellows** [comment]
Looks like most people reporting bugs have administrative powers, and so have a non-pointless menu.

**Comment by pauljherring** [comment]
Only 3 (PJH,BZ,BL) of us have admin, 3 more (AB, Yami, Alice) have mod (if all of them are even reporting) - everyone else is getting your pointless menu.

**Comment by dkfellows** [comment]
Err, I meant across the whole nodeBB community. Not this installation. :wink:

**Comment by pauljherring** [comment]
I rather suspect the same was of Discourse...

At least outside of our installation of it and the subsequent mass-ban.

**Comment by blakeyrat-dailywtf** [comment]
It used to be weirder when there were all these strange options in there like "make into normal thread" and such-- Ben L disabled some plug-in to get it back to this "sane" state.

**Comment by BenLubar** [comment]
Looks like the dropdown menu got removed at some point.
