### ISSUE TITLE
"Mark as read" > All, unexpected behaviour

### ISSUE THREAD

**Issue by pauljherring** [apxltd/what-bugs#87]
"Mark as read" > All should, IMO, mark all the currently selected section of posts.

For example:

![screenshot from 2016-04-06 10 31 36](https://cloud.githubusercontent.com/assets/3939886/14312135/ce28af98-fbe2-11e5-9127-3d97442ac1c5.png)

Mark as Read > All

Expected: Mark all unread posts as read (except for the issue raised in #77, which applies to all Expected/Actual comments below)
Actual: Marks all unread posts as read

![screenshot from 2016-04-06 10 33 29](https://cloud.githubusercontent.com/assets/3939886/14312188/111f5ffe-fbe3-11e5-9c9c-7f6069642611.png)

Expected - option 1: Mark all unread posts in General only as read 
Expected - option 2: Mark all unread posts in General and sub-categories only as read 
Actual: Marks **all** unread posts as read

**Comment by pauljherring** [comment]
Ok - just realised and noticed that the Mark as Read dropdown also includes all the categories (`order by random` - see #88.)

Not sure what to do about that UI/UX...

**Comment by jaloopa** [comment]
On a related point, the All option should have a confirmation step before actually marking everything as read. It's quite easy to fat finger on mobile

**Comment by pauljherring** [comment]
Slightly more relevant - how many threads would be marked "as read" if clicking `all` here?

![screenshot from 2016-04-06 15 57 09](https://cloud.githubusercontent.com/assets/3939886/14321271/71c5eecc-fc10-11e5-98fe-5b90748db94a.png)

[poll]
- 3
- 4

[/poll]

[spoiler]4[/spoiler]

And if `There is a new post` appears just appeared a fraction of a second before hitting `All`?
