### ISSUE TITLE
Emojified avatars are broken

### ISSUE THREAD

**Issue by yamikuronue** [apxltd/what-bugs#9]
Before the import, in the lounge, people sometimes used avatars as emoji by adding `class="emoji` into the img tag. After the import, this has been sanitized away, and the stories look hideous now. 

Sample:
![image](https://cloud.githubusercontent.com/assets/1219256/13922307/0aa73662-ef52-11e5-8bb8-a23cdb551543.png)

**Comment by BenLubar** [comment]
Fixed in BenLubar/nodebb-plugin-htmlcleaner@9f218d1860239a920947e13c19681127c6e0051e
