### ISSUE TITLE
Text editor shortcuts don't exist

### ISSUE THREAD

**Issue by blakeyrat-dailywtf** [apxltd/what-bugs#90]
I know someone complained about the keyboard shortcuts, because they were using some dumb browser plugin, but I think we've thrown the baby out with the bathwater.

Control-B should always do Bold, and control-I should always do Italics.

Let's put those shortcuts back, so NodeBB is complaint with 99.99999999% other software with styled text fields out there.

**Comment by 2piix** [comment]
Let's get Vim style keyboard shortcuts installed too!  This is probably more important than Blakey's dumb idea, btw.

**Comment by halcyon1234** [comment]
Concur.  Hijacking browser is bad.  Capturing bog-standard text editor shortcuts while typing a text message in a text field is good.

ctrl-b for **bold****strong text**

**Comment by halcyon1234** [comment]
Concur.  Hijacking browser is bad.  Capturing bog-standard text editor shortcuts while typing a text message in a text field is good.

ctrl-b for **bold****strong text**

**Comment by halcyon1234** [comment]
Fuck you Github
