### ISSUE TITLE
Highlight-reply breaks on titles with comma

### ISSUE THREAD

**Issue by halcyon1234** [apxltd/what-bugs#91]
https://what.thedailywtf.com/topic/19647/oh-look-it-isn-t-so-hard-to-fix-jellypotato-on-image-loads/7

@Lorne-Kates said in [Oh look:

**Comment by BenLubar** [comment]
Oh wow.

NodeBB/nodebb-plugin-composer-default#30 vs NodeBB/nodebb-plugin-composer-default@77e0c3d94cc33b247a206fbc41770563285bb887

@julianlam @RaceProUK what just happened here?

**Comment by RaceProUK** [comment]
Fixing one issue exposed another; it happens :wink:

**Comment by BenLubar** [comment]
But the PR wasn't merged and it contained the non-hacky fix for the bug that was fixed by that commit.

**Comment by RaceProUK** [comment]
Huh… good point

**Comment by julianlam** [comment]
Oh really? I must've forgotten about this PR... if reverting my commit and
applying that PR works, then I'll merge.

**Comment by BenLubar** [comment]
```
$ git revert 77e0c3d94cc33b247a206fbc41770563285bb887
[master 14204f9] Revert "fixing issue where quoting a post from a topic that began with a square bracket caused the translation to fail"
 1 file changed, 2 insertions(+), 5 deletions(-)
$ git merge RaceProUK/master 
Merge made by the 'recursive' strategy.
 static/lib/composer.js | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)
```

![image](https://cloud.githubusercontent.com/assets/4257305/14366177/25782b30-fcd7-11e5-9c2c-e003c9815efd.png)

@julianlam :+1:

**Comment by julianlam** [comment]
Cheers! 

@psychobunny can you please revert my commit (see Ben's comment) and merge @RaceProUK's PR?

**Comment by NedFodder** [comment]
Maybe this should reopened?  [Here](https://what.thedailywtf.com/topic/19653/dear-blakeyrat-i-fixed-the-css-signed-the-desktop-view/16) is a topic title with a mention.

**Comment by BenLubar** [comment]
@NedFodder that looks like a bug with the mentions plugin. It shouldn't be converting mentions that are inside `<a>` tags.

**Comment by NedFodder** [comment]
OK, now it does look like the original bug is [back](https://what.thedailywtf.com/topic/19579/changing-jobs-wtfs-are-always-greener-on-the-neighbor-s-lawn/5)

![capture](https://cloud.githubusercontent.com/assets/18215743/14435612/c3075c56-ffe6-11e5-8d25-1f94d5a6d29f.PNG)

EDIT: [Here](https://what.thedailywtf.com/topic/19647/oh-look-it-isn-t-so-hard-to-fix-jellypotato-on-image-loads/7) is a link that more people can get to.  It says `[Oh look:` again.

**Comment by BenLubar** [comment]
@NedFodder https://what.thedailywtf.com/topic/19632/iframely-links-to-post/9
