### ISSUE TITLE
OAuth2 is broken

### ISSUE THREAD

**Issue by 2piix** [apxltd/what-bugs#92]
I was using the Google OAuth2 provider to sign in, since my email/password combination doesn't work.  Now Google does not work either.  It's just missing.  Policy?

Not giving my username to avoid doxxing myself.

**Comment by pauljherring** [comment]
Feel free to email me (wer8dtf9t9@snkmail.com) if you want help logging back in - OAuth (http://what.thedailywtf.com/auth/google) still works for me however.

**Comment by 2piix** [comment]
Thanks PJH, I got it sorted out.

The OAuth issue was strange.  All the options except for Github disappeared for a while.  I guess this can be marked as closed though.
