### ISSUE TITLE
@mention in thread title breaks quoted post's post link

### ISSUE THREAD

**Issue by coderpatsy** [apxltd/what-bugs#93]
![quote_bug](https://cloud.githubusercontent.com/assets/13140934/14401706/b8cd2b1e-fdd7-11e5-9fe9-5e345b69780e.png)

Post: https://what.thedailywtf.com/topic/19653/dear-blakeyrat-i-fixed-the-css-signed-the-desktop-view/14

**Comment by BenLubar** [comment]
Moved to julianlam/nodebb-plugin-mentions#71
