### ISSUE TITLE
Make 'replied to post' indicator a hyperlink

### ISSUE THREAD

**Issue by coderpatsy** [apxltd/what-bugs#94]
E.g. make the ![replied_to_blakey](https://cloud.githubusercontent.com/assets/13140934/14405058/05783f74-fe43-11e5-9361-f67806e82f3b.png) box in https://what.thedailywtf.com/topic/19653/dear-blakeyrat-i-fixed-the-css-signed-the-desktop-view/14 a hyperlink to [post 9](https://what.thedailywtf.com/topic/19653/dear-blakeyrat-i-fixed-the-css-signed-the-desktop-view/9).

This allows one to directly open the replied to post in a new tab and not lose their place in a conversation. Plus disabled javascript etc.

**Comment by BenLubar** [comment]
It might be harder than I first thought... Here's the code that runs when you click on those: https://github.com/NodeBB/NodeBB/blob/v1.0.2/public/src/client/topic.js#L188-L207

**Comment by coderpatsy** [comment]
And this is fixed. Thanks Ben! (feel free to ref your PRs)

**Comment by BenLubar** [comment]
https://github.com/NodeBB/NodeBB/pull/4853
https://github.com/NodeBB/nodebb-theme-persona/pull/300
