### ISSUE TITLE
Please consider lending your support...

### ISSUE THREAD

**Issue by lolwhat** [apxltd/what-bugs#95]
... to having the following bug fixed in `nodebb-plugin-sso-google`:

https://community.nodebb.org/topic/8486/nodebb-doesn-t-handle-multiple-google-logins

This bug hits any NodeBB site with Google SSO integration. Yes, I'm being somewhat Blakey about it, but it's a useability issue that plenty of other sites out there with such integration have already solved.

**Comment by BenLubar** [comment]
![:arrows:](https://what.thedailywtf.com/plugins/nodebb-plugin-emoji-static/static/images/tdwtf/arrows.png)

julianlam/nodebb-plugin-sso-google#18

**Comment by lolwhat** [comment]
Julian has fixed the issue. The changes were evidently deployed to WTDWTF. I've verified.
