### ISSUE TITLE
Composer + Markdown: buttons and trailing spaces

### ISSUE THREAD

**Issue by NedFodder** [apxltd/what-bugs#96]
A fairly common thing to do in the composer is to type some text, double-click a word, and click on one of the formatting buttons (bold, italic, etc).  The Markdown plugin wraps the selected text with the formatting. This breaks on Windows because double-clicking a word also selects the trailing space.  You end up with _this _situation. (And now I know GitHub has the same problem!)

The Markdown plugin needs to remove leading and trailing spaces from the selection before wrapping the text.

**Comment by BenLubar** [comment]
It's not the markdown plugin, it's the composer.

Before I write a fix, would it make sense for _any_ of the buttons to not remove leading/trailing spaces from the selection before acting?

**Comment by BenLubar** [comment]
Looks like the code to change would be [this function](https://github.com/NodeBB/nodebb-plugin-composer-default/blob/84f50f2b5c20f1928b5e33966d0e885ec9dd1ff0/static/lib/composer/controls.js#L22) unless there might be a reason to keep leading/trailing spaces in the selection on some buttons.

**Comment by pauljherring** [comment]
When it is deliberately selected?

**Comment by BenLubar** [comment]
@pauljherring there's no way to determine whether someone deliberately or accidentally included leading/trailing spaces in their selection. It's probably less bad to always ignore leading/trailing spaces than to always include them.

**Comment by NedFodder** [comment]
The composer is more general. There may be cases where it makes sense to have the spaces, but changing it there would make it impossible for _any_ plugins to select the spaces.  The markdown plugin is more specific. The core of markdown only works when the formatting is {space}{special character}{text with no leading/trailing spaces}{special character}{space}.  So that's why I suggested it should be fixed in the markdown plugin.

**Comment by julianlam** [comment]
If I had text _one two three_ and double clicked "two", on Windows, it would select _one `two`three_?

If it is then bolded, is the space re-added between `two` and `three`?

**Comment by julianlam** [comment]
@BenLubar perhaps my comment should have been in reference to NodeBB/nodebb-plugin-composer-default#33 :stuck_out_tongue:

**Comment by NedFodder** [comment]
@julianlam On Windows, double clicking "two" selects one `two`three. Then clicking on the italic button produces `one *two *three`, which looks like one *two *three (same on GitHub and NodeBB, for the same reason).  No extra space gets inserted between two and three.

**Comment by julianlam** [comment]
Thanks @NedFodder, what I meant is whether the space is _corrected_ in @BenLubar's pull request.

**Comment by NedFodder** [comment]
Ah. From my understanding, his code inserts the `leading` string after any leading spaces, and the `trailing` string before any trailing spaces. So one `two`three becomes `one   *two*   three`.

**Comment by BenLubar** [comment]
@julianlam it moves the space outside the wrapper. As a special case, a selection that is entirely whitespace does not get affected by this change.

@NedFodder that is correct.
